use_frameworks!

platform :ios, '8.0'

target 'KZWWebViewController_Category_Example' do
  pod 'KZWWebViewController_Category', :path => '../'
  pod 'KZWWebViewController'

  target 'KZWWebViewController_Category_Tests' do
    inherit! :search_paths

    
  end
end
